# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-demo"
client_id = "e89e28215e8ca04836b7489ba465258b"
application_url = "https://small-helicopter-diagnosis-eleven.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://small-helicopter-diagnosis-eleven.trycloudflare.com/auth/callback",
  "https://small-helicopter-diagnosis-eleven.trycloudflare.com/auth/shopify/callback",
  "https://small-helicopter-diagnosis-eleven.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "petsdeli-dev.myshopify.com"
